[versions]
agp = "8.8.0"
annotationJvm = "1.9.1"

[libraries]
annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }

